linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt
    - goimports
