// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnswer = `-- name: CreateAnswer :one

INSERT INTO courses.answers (
    question_id, text, is_correct, order_index
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, question_id, text, is_correct, order_index, created_at, updated_at
`

type CreateAnswerParams struct {
	QuestionID pgtype.UUID
	Text       string
	IsCorrect  bool
	OrderIndex int32
}

// answers.is_correct is server-only data (Non-Negotiable #1). The client path
// uses ListAnswersForClient (no is_correct); only the grading path reads the key.
func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (CoursesAnswer, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.QuestionID,
		arg.Text,
		arg.IsCorrect,
		arg.OrderIndex,
	)
	var i CoursesAnswer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnswersByQuestion = `-- name: DeleteAnswersByQuestion :exec
DELETE FROM courses.answers
WHERE question_id = $1
`

func (q *Queries) DeleteAnswersByQuestion(ctx context.Context, questionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnswersByQuestion, questionID)
	return err
}

const listAnswersByQuestion = `-- name: ListAnswersByQuestion :many
SELECT id, question_id, text, is_correct, order_index, created_at, updated_at FROM courses.answers
WHERE question_id = $1
ORDER BY order_index ASC, id ASC
`

// ListAnswersByQuestion is server-internal: it includes is_correct for grading
// and teacher-facing reads. Never map it onto a client DTO.
func (q *Queries) ListAnswersByQuestion(ctx context.Context, questionID pgtype.UUID) ([]CoursesAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswersByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesAnswer{}
	for rows.Next() {
		var i CoursesAnswer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersForClient = `-- name: ListAnswersForClient :many
SELECT id, question_id, text, order_index
FROM courses.answers
WHERE question_id = $1
ORDER BY order_index ASC, id ASC
`

type ListAnswersForClientRow struct {
	ID         pgtype.UUID
	QuestionID pgtype.UUID
	Text       string
	OrderIndex int32
}

// ListAnswersForClient renders options to the student. It omits is_correct at
// the SQL level, so the leak is structurally impossible in the generated struct.
func (q *Queries) ListAnswersForClient(ctx context.Context, questionID pgtype.UUID) ([]ListAnswersForClientRow, error) {
	rows, err := q.db.Query(ctx, listAnswersForClient, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnswersForClientRow{}
	for rows.Next() {
		var i ListAnswersForClientRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
