// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :exec
INSERT INTO auth.admin_audit_log (actor_id, action, target_type, target_id, details)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAdminAuditLogParams struct {
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   pgtype.UUID
	Details    []byte
}

func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAdminAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
	)
	return err
}

type AuthAdminAuditLog struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   pgtype.UUID
	Details    []byte
	CreatedAt  pgtype.Timestamptz
}
