// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// CoursesCertificate is the row type for courses.certificates.
type CoursesCertificate struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	CourseID  pgtype.UUID
	Serial    string
	FileKey   *string
	IssuedAt  pgtype.Timestamptz
}

const createCertificateIfNotExists = `-- name: CreateCertificateIfNotExists :one
INSERT INTO courses.certificates (student_id, course_id, serial)
VALUES ($1, $2, $3)
ON CONFLICT (student_id, course_id) DO NOTHING
RETURNING id, student_id, course_id, serial, file_key, issued_at
`

type CreateCertificateIfNotExistsParams struct {
	StudentID pgtype.UUID
	CourseID  pgtype.UUID
	Serial    string
}

// CreateCertificateIfNotExists returns nil, nil when the row already exists
// (ON CONFLICT DO NOTHING). Callers must check for pgx.ErrNoRows to detect
// the no-insert case.
func (q *Queries) CreateCertificateIfNotExists(ctx context.Context, arg CreateCertificateIfNotExistsParams) (CoursesCertificate, error) {
	row := q.db.QueryRow(ctx, createCertificateIfNotExists, arg.StudentID, arg.CourseID, arg.Serial)
	var i CoursesCertificate
	err := row.Scan(&i.ID, &i.StudentID, &i.CourseID, &i.Serial, &i.FileKey, &i.IssuedAt)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, student_id, course_id, serial, file_key, issued_at
FROM courses.certificates
WHERE id = $1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id pgtype.UUID) (CoursesCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i CoursesCertificate
	err := row.Scan(&i.ID, &i.StudentID, &i.CourseID, &i.Serial, &i.FileKey, &i.IssuedAt)
	return i, err
}

const getCertificateByStudentCourse = `-- name: GetCertificateByStudentCourse :one
SELECT id, student_id, course_id, serial, file_key, issued_at
FROM courses.certificates
WHERE student_id = $1 AND course_id = $2
`

func (q *Queries) GetCertificateByStudentCourse(ctx context.Context, studentID pgtype.UUID, courseID pgtype.UUID) (CoursesCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByStudentCourse, studentID, courseID)
	var i CoursesCertificate
	err := row.Scan(&i.ID, &i.StudentID, &i.CourseID, &i.Serial, &i.FileKey, &i.IssuedAt)
	return i, err
}

const getCertificateBySerial = `-- name: GetCertificateBySerial :one
SELECT id, student_id, course_id, serial, file_key, issued_at
FROM courses.certificates
WHERE serial = $1
`

func (q *Queries) GetCertificateBySerial(ctx context.Context, serial string) (CoursesCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateBySerial, serial)
	var i CoursesCertificate
	err := row.Scan(&i.ID, &i.StudentID, &i.CourseID, &i.Serial, &i.FileKey, &i.IssuedAt)
	return i, err
}

const setCertificateFileKey = `-- name: SetCertificateFileKey :exec
UPDATE courses.certificates SET file_key = $2 WHERE id = $1
`

func (q *Queries) SetCertificateFileKey(ctx context.Context, id pgtype.UUID, fileKey string) error {
	_, err := q.db.Exec(ctx, setCertificateFileKey, id, fileKey)
	return err
}

const listCertificatesByStudent = `-- name: ListCertificatesByStudent :many
SELECT id, student_id, course_id, serial, file_key, issued_at
FROM courses.certificates
WHERE student_id = $1
ORDER BY issued_at DESC
`

func (q *Queries) ListCertificatesByStudent(ctx context.Context, studentID pgtype.UUID) ([]CoursesCertificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesCertificate
	for rows.Next() {
		var i CoursesCertificate
		if err := rows.Scan(&i.ID, &i.StudentID, &i.CourseID, &i.Serial, &i.FileKey, &i.IssuedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
