// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, discount_type, discount_value, max_uses, used_count, expires_at, applicable_to, course_ids, created_at, updated_at FROM payments.coupons WHERE code = $1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (PaymentsCoupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, code)
	var i PaymentsCoupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.ApplicableTo,
		&i.CourseIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCouponUse = `-- name: IncrementCouponUse :execrows
UPDATE payments.coupons
SET used_count = used_count + 1, updated_at = now()
WHERE id = $1
  AND (max_uses IS NULL OR used_count < max_uses)
`

// IncrementCouponUse bumps used_count only while it is still below max_uses (or
// max_uses is NULL = unlimited). :execrows reports redeemed=false (0 rows) when
// the coupon is already exhausted, even under concurrent fulfillment. Called only
// inside the successful-payment transaction.
func (q *Queries) IncrementCouponUse(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementCouponUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
