// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses.courses (
    teacher_id, title, slug, description, short_description, subject, grade,
    thumbnail_url, price, currency, is_free, is_published, language, level,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, teacher_id, title, slug, description, short_description, subject, grade, thumbnail_url, price, currency, is_free, is_published, language, level, total_duration_seconds, total_lessons, rating_avg, enrollment_count, metadata, created_at, updated_at, deleted_at
`

type CreateCourseParams struct {
	TeacherID        pgtype.UUID
	Title            string
	Slug             string
	Description      string
	ShortDescription *string
	Subject          string
	Grade            int32
	ThumbnailUrl     *string
	Price            pgtype.Numeric
	Currency         string
	IsFree           bool
	IsPublished      bool
	Language         string
	Level            string
	Metadata         []byte
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.TeacherID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.Subject,
		arg.Grade,
		arg.ThumbnailUrl,
		arg.Price,
		arg.Currency,
		arg.IsFree,
		arg.IsPublished,
		arg.Language,
		arg.Level,
		arg.Metadata,
	)
	var i CoursesCourse
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.Subject,
		&i.Grade,
		&i.ThumbnailUrl,
		&i.Price,
		&i.Currency,
		&i.IsFree,
		&i.IsPublished,
		&i.Language,
		&i.Level,
		&i.TotalDurationSeconds,
		&i.TotalLessons,
		&i.RatingAvg,
		&i.EnrollmentCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, teacher_id, title, slug, description, short_description, subject, grade, thumbnail_url, price, currency, is_free, is_published, language, level, total_duration_seconds, total_lessons, rating_avg, enrollment_count, metadata, created_at, updated_at, deleted_at FROM courses.courses
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i CoursesCourse
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.Subject,
		&i.Grade,
		&i.ThumbnailUrl,
		&i.Price,
		&i.Currency,
		&i.IsFree,
		&i.IsPublished,
		&i.Language,
		&i.Level,
		&i.TotalDurationSeconds,
		&i.TotalLessons,
		&i.RatingAvg,
		&i.EnrollmentCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, teacher_id, title, slug, description, short_description, subject, grade, thumbnail_url, price, currency, is_free, is_published, language, level, total_duration_seconds, total_lessons, rating_avg, enrollment_count, metadata, created_at, updated_at, deleted_at FROM courses.courses
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i CoursesCourse
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.Subject,
		&i.Grade,
		&i.ThumbnailUrl,
		&i.Price,
		&i.Currency,
		&i.IsFree,
		&i.IsPublished,
		&i.Language,
		&i.Level,
		&i.TotalDurationSeconds,
		&i.TotalLessons,
		&i.RatingAvg,
		&i.EnrollmentCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, teacher_id, title, slug, description, short_description, subject, grade, thumbnail_url, price, currency, is_free, is_published, language, level, total_duration_seconds, total_lessons, rating_avg, enrollment_count, metadata, created_at, updated_at, deleted_at FROM courses.courses
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR subject = $1)
  AND ($2::int IS NULL OR grade = $2)
  AND ($3::bool IS NULL OR is_published = $3)
  AND ($4::uuid IS NULL OR teacher_id = $4)
  AND (
      $5::timestamptz IS NULL
      OR (created_at, id) < ($5::timestamptz, $6::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListCoursesParams struct {
	Subject        *string
	Grade          *int32
	IsPublished    *bool
	TeacherID      pgtype.UUID
	AfterCreatedAt pgtype.Timestamptz
	AfterID        pgtype.UUID
	RowLimit       int32
}

// Keyset (cursor) pagination ordered by (created_at, id) DESC. Nullable filter
// args are ignored when NULL. after_created_at/after_id is the decoded cursor.
func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]CoursesCourse, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Subject,
		arg.Grade,
		arg.IsPublished,
		arg.TeacherID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesCourse{}
	for rows.Next() {
		var i CoursesCourse
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.Subject,
			&i.Grade,
			&i.ThumbnailUrl,
			&i.Price,
			&i.Currency,
			&i.IsFree,
			&i.IsPublished,
			&i.Language,
			&i.Level,
			&i.TotalDurationSeconds,
			&i.TotalLessons,
			&i.RatingAvg,
			&i.EnrollmentCount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeCourseCounters = `-- name: RecomputeCourseCounters :exec
UPDATE courses.courses c
SET total_lessons = sub.cnt,
    total_duration_seconds = sub.dur
FROM (
    SELECT COUNT(*)::int AS cnt,
           COALESCE(SUM(duration_seconds), 0)::int AS dur
    FROM courses.lessons
    WHERE course_id = $1 AND deleted_at IS NULL
) AS sub
WHERE c.id = $1 AND c.deleted_at IS NULL
`

// Recompute the denormalized lesson counters from the live (non-deleted)
// lessons. Run inside the same transaction as the lesson mutation that
// triggered it so the course row stays consistent.
func (q *Queries) RecomputeCourseCounters(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recomputeCourseCounters, id)
	return err
}

const softDeleteCourse = `-- name: SoftDeleteCourse :exec
UPDATE courses.courses
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCourse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCourse, id)
	return err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses.courses
SET title = $2,
    description = $3,
    short_description = $4,
    subject = $5,
    grade = $6,
    thumbnail_url = $7,
    price = $8,
    currency = $9,
    is_free = $10,
    is_published = $11,
    language = $12,
    level = $13,
    metadata = $14
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, teacher_id, title, slug, description, short_description, subject, grade, thumbnail_url, price, currency, is_free, is_published, language, level, total_duration_seconds, total_lessons, rating_avg, enrollment_count, metadata, created_at, updated_at, deleted_at
`

type UpdateCourseParams struct {
	ID               pgtype.UUID
	Title            string
	Description      string
	ShortDescription *string
	Subject          string
	Grade            int32
	ThumbnailUrl     *string
	Price            pgtype.Numeric
	Currency         string
	IsFree           bool
	IsPublished      bool
	Language         string
	Level            string
	Metadata         []byte
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ShortDescription,
		arg.Subject,
		arg.Grade,
		arg.ThumbnailUrl,
		arg.Price,
		arg.Currency,
		arg.IsFree,
		arg.IsPublished,
		arg.Language,
		arg.Level,
		arg.Metadata,
	)
	var i CoursesCourse
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.Subject,
		&i.Grade,
		&i.ThumbnailUrl,
		&i.Price,
		&i.Currency,
		&i.IsFree,
		&i.IsPublished,
		&i.Language,
		&i.Level,
		&i.TotalDurationSeconds,
		&i.TotalLessons,
		&i.RatingAvg,
		&i.EnrollmentCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
