// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO payments.enrollments (id, student_id, course_id, source, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (student_id, course_id) DO NOTHING
RETURNING id, student_id, course_id, enrolled_at, expires_at, source, created_at, updated_at
`

type CreateEnrollmentParams struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	CourseID  pgtype.UUID
	Source    string
	ExpiresAt pgtype.Timestamptz
}

// CreateEnrollment grants access once. ON CONFLICT (student_id, course_id) DO
// NOTHING makes a re-processed payment a no-op insert (exactly-once grant); the
// caller treats a 0-row result as "already enrolled", not an error.
func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (PaymentsEnrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.StudentID,
		arg.CourseID,
		arg.Source,
		arg.ExpiresAt,
	)
	var i PaymentsEnrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enrollmentExists = `-- name: EnrollmentExists :one
SELECT EXISTS (
    SELECT 1 FROM payments.enrollments
    WHERE student_id = $1 AND course_id = $2
)
`

type EnrollmentExistsParams struct {
	StudentID pgtype.UUID
	CourseID  pgtype.UUID
}

func (q *Queries) EnrollmentExists(ctx context.Context, arg EnrollmentExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, enrollmentExists, arg.StudentID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveEnrollment = `-- name: GetActiveEnrollment :one
SELECT id, student_id, course_id, enrolled_at, expires_at, source, created_at, updated_at FROM payments.enrollments
WHERE student_id = $1 AND course_id = $2
  AND (expires_at IS NULL OR expires_at > now())
`

type GetActiveEnrollmentParams struct {
	StudentID pgtype.UUID
	CourseID  pgtype.UUID
}

// GetActiveEnrollment returns the enrollment only when it grants access now
// (no expiry, or not yet expired).
func (q *Queries) GetActiveEnrollment(ctx context.Context, arg GetActiveEnrollmentParams) (PaymentsEnrollment, error) {
	row := q.db.QueryRow(ctx, getActiveEnrollment, arg.StudentID, arg.CourseID)
	var i PaymentsEnrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnrollmentsByStudent = `-- name: ListEnrollmentsByStudent :many
SELECT id, student_id, course_id, enrolled_at, expires_at, source, created_at, updated_at FROM payments.enrollments
WHERE student_id = $1
ORDER BY enrolled_at DESC
LIMIT $2
`

type ListEnrollmentsByStudentParams struct {
	StudentID pgtype.UUID
	Limit     int32
}

func (q *Queries) ListEnrollmentsByStudent(ctx context.Context, arg ListEnrollmentsByStudentParams) ([]PaymentsEnrollment, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsByStudent, arg.StudentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsEnrollment{}
	for rows.Next() {
		var i PaymentsEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CourseID,
			&i.EnrolledAt,
			&i.ExpiresAt,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
