// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_attempts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExamAttemptForGrading = `-- name: ClaimExamAttemptForGrading :one
UPDATE courses.exam_attempts
SET status = $2,
    answers_snapshot = $3,
    submitted_at = $4
WHERE id = $1 AND status = 'in_progress'
RETURNING id, exam_id, student_id, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at
`

type ClaimExamAttemptForGradingParams struct {
	ID              pgtype.UUID
	Status          string
	AnswersSnapshot []byte
	SubmittedAt     pgtype.Timestamptz
}

// Race-safe transition out of in_progress (spec §9.2): WHERE status='in_progress'
// ensures only the first writer (late client submit OR sweeper) flips the row;
// the loser matches no row and no-ops. $2 is 'submitted' or 'expired'.
func (q *Queries) ClaimExamAttemptForGrading(ctx context.Context, arg ClaimExamAttemptForGradingParams) (CoursesExamAttempt, error) {
	row := q.db.QueryRow(ctx, claimExamAttemptForGrading,
		arg.ID,
		arg.Status,
		arg.AnswersSnapshot,
		arg.SubmittedAt,
	)
	var i CoursesExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExamAttempt = `-- name: CreateExamAttempt :one
INSERT INTO courses.exam_attempts (
    exam_id, student_id, answers_snapshot, status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, exam_id, student_id, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at
`

type CreateExamAttemptParams struct {
	ExamID          pgtype.UUID
	StudentID       pgtype.UUID
	AnswersSnapshot []byte
	Status          string
}

func (q *Queries) CreateExamAttempt(ctx context.Context, arg CreateExamAttemptParams) (CoursesExamAttempt, error) {
	row := q.db.QueryRow(ctx, createExamAttempt,
		arg.ExamID,
		arg.StudentID,
		arg.AnswersSnapshot,
		arg.Status,
	)
	var i CoursesExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findExpiredExamAttempts = `-- name: FindExpiredExamAttempts :many
SELECT a.id, a.exam_id, a.student_id, a.started_at, a.submitted_at, a.score, a.percentage, a.answers_snapshot, a.status, a.created_at, a.updated_at FROM courses.exam_attempts a
JOIN courses.exams e ON e.id = a.exam_id
WHERE a.status = 'in_progress'
  AND a.started_at + (e.duration_minutes * interval '1 minute') < $1
ORDER BY a.started_at ASC
LIMIT $2
`

type FindExpiredExamAttemptsParams struct {
	StartedAt pgtype.Timestamptz
	Limit     int32
}

// In-progress attempts whose server-side timer has elapsed, for the auto-submit
// sweeper (spec §9.2). The deadline is derived from exams.duration_minutes; the
// client timer is display-only (Non-Negotiable #2).
func (q *Queries) FindExpiredExamAttempts(ctx context.Context, arg FindExpiredExamAttemptsParams) ([]CoursesExamAttempt, error) {
	rows, err := q.db.Query(ctx, findExpiredExamAttempts, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesExamAttempt{}
	for rows.Next() {
		var i CoursesExamAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.StudentID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.Percentage,
			&i.AnswersSnapshot,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveExamAttempt = `-- name: GetActiveExamAttempt :one
SELECT id, exam_id, student_id, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at FROM courses.exam_attempts
WHERE student_id = $1 AND exam_id = $2 AND status = 'in_progress'
ORDER BY started_at DESC
LIMIT 1
`

type GetActiveExamAttemptParams struct {
	StudentID pgtype.UUID
	ExamID    pgtype.UUID
}

// The student's current in-progress sitting of an exam, if any.
func (q *Queries) GetActiveExamAttempt(ctx context.Context, arg GetActiveExamAttemptParams) (CoursesExamAttempt, error) {
	row := q.db.QueryRow(ctx, getActiveExamAttempt, arg.StudentID, arg.ExamID)
	var i CoursesExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExamAttemptByID = `-- name: GetExamAttemptByID :one
SELECT id, exam_id, student_id, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at FROM courses.exam_attempts
WHERE id = $1 AND student_id = $2
`

type GetExamAttemptByIDParams struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
}

// Filters by student_id to prevent IDOR (Non-Negotiable #7).
func (q *Queries) GetExamAttemptByID(ctx context.Context, arg GetExamAttemptByIDParams) (CoursesExamAttempt, error) {
	row := q.db.QueryRow(ctx, getExamAttemptByID, arg.ID, arg.StudentID)
	var i CoursesExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExamAttemptStats = `-- name: GetExamAttemptStats :one
SELECT
    count(*)                                                   AS total_attempts,
    coalesce(avg(a.percentage), 0)::float8                     AS avg_percentage,
    count(*) FILTER (WHERE a.score >= e.pass_marks)            AS passed_count
FROM courses.exam_attempts a
JOIN courses.exams e ON e.id = a.exam_id
WHERE a.exam_id = $1 AND a.status = 'graded'
`

type GetExamAttemptStatsRow struct {
	TotalAttempts int64
	AvgPercentage float64
	PassedCount   int64
}

// Teacher/admin exam stats (§9.3): how many graded attempts, the average
// percentage, and how many passed (score >= the exam's pass_marks).
func (q *Queries) GetExamAttemptStats(ctx context.Context, examID pgtype.UUID) (GetExamAttemptStatsRow, error) {
	row := q.db.QueryRow(ctx, getExamAttemptStats, examID)
	var i GetExamAttemptStatsRow
	err := row.Scan(&i.TotalAttempts, &i.AvgPercentage, &i.PassedCount)
	return i, err
}

const gradeExamAttempt = `-- name: GradeExamAttempt :one
UPDATE courses.exam_attempts
SET score = $2,
    percentage = $3,
    submitted_at = now(),
    status = 'graded'
WHERE id = $1
RETURNING id, exam_id, student_id, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at
`

type GradeExamAttemptParams struct {
	ID         pgtype.UUID
	Score      pgtype.Numeric
	Percentage pgtype.Numeric
}

func (q *Queries) GradeExamAttempt(ctx context.Context, arg GradeExamAttemptParams) (CoursesExamAttempt, error) {
	row := q.db.QueryRow(ctx, gradeExamAttempt, arg.ID, arg.Score, arg.Percentage)
	var i CoursesExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExamAttemptsByStudent = `-- name: ListExamAttemptsByStudent :many
SELECT id, exam_id, student_id, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at FROM courses.exam_attempts
WHERE student_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListExamAttemptsByStudent(ctx context.Context, studentID pgtype.UUID) ([]CoursesExamAttempt, error) {
	rows, err := q.db.Query(ctx, listExamAttemptsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesExamAttempt{}
	for rows.Next() {
		var i CoursesExamAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.StudentID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.Percentage,
			&i.AnswersSnapshot,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradedExamAttemptsBySubject = `-- name: ListGradedExamAttemptsBySubject :many
SELECT a.id, a.exam_id, a.student_id, a.started_at, a.submitted_at, a.score, a.percentage, a.answers_snapshot, a.status, a.created_at, a.updated_at FROM courses.exam_attempts a
JOIN courses.exams e ON e.id = a.exam_id
WHERE a.student_id = $1
  AND e.subject = $2
  AND a.status = 'graded'
ORDER BY a.submitted_at ASC, a.started_at ASC
`

type ListGradedExamAttemptsBySubjectParams struct {
	StudentID pgtype.UUID
	Subject   string
}

// Score trend (§9.3): a student's graded attempts for a subject, oldest first, so
// the caller can plot score over consecutive attempts. Joins exams for subject.
func (q *Queries) ListGradedExamAttemptsBySubject(ctx context.Context, arg ListGradedExamAttemptsBySubjectParams) ([]CoursesExamAttempt, error) {
	rows, err := q.db.Query(ctx, listGradedExamAttemptsBySubject, arg.StudentID, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesExamAttempt{}
	for rows.Next() {
		var i CoursesExamAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.StudentID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.Percentage,
			&i.AnswersSnapshot,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExamAttempt = `-- name: UpdateExamAttempt :one
UPDATE courses.exam_attempts
SET answers_snapshot = $2,
    status = $3,
    submitted_at = $4
WHERE id = $1
RETURNING id, exam_id, student_id, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at
`

type UpdateExamAttemptParams struct {
	ID              pgtype.UUID
	AnswersSnapshot []byte
	Status          string
	SubmittedAt     pgtype.Timestamptz
}

// Auto-save and status transitions; the immutable started_at timer column is
// never touched here.
func (q *Queries) UpdateExamAttempt(ctx context.Context, arg UpdateExamAttemptParams) (CoursesExamAttempt, error) {
	row := q.db.QueryRow(ctx, updateExamAttempt,
		arg.ID,
		arg.AnswersSnapshot,
		arg.Status,
		arg.SubmittedAt,
	)
	var i CoursesExamAttempt
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentExamPoints = `-- name: GetStudentExamPoints :one
SELECT
    COALESCE(SUM(best.best_score), 0)::float8      AS total_points,
    COUNT(*)                                       AS exam_count,
    COALESCE(AVG(best.best_percentage), 0)::float8 AS avg_percentage
FROM (
    SELECT exam_id,
           MAX(score)      AS best_score,
           MAX(percentage) AS best_percentage
    FROM courses.exam_attempts
    WHERE student_id = $1 AND status = 'graded' AND score IS NOT NULL
    GROUP BY exam_id
) best
`

type GetStudentExamPointsRow struct {
	TotalPoints   float64
	ExamCount     int64
	AvgPercentage float64
}

// A student's cumulative exam points (§9.3): the best graded score per exam,
// summed, plus how many distinct exams they've completed and the average of
// those best percentages. Taking the best attempt per exam means retakes raise
// the total only by the improvement — they never double-count.
func (q *Queries) GetStudentExamPoints(ctx context.Context, studentID pgtype.UUID) (GetStudentExamPointsRow, error) {
	row := q.db.QueryRow(ctx, getStudentExamPoints, studentID)
	var i GetStudentExamPointsRow
	err := row.Scan(&i.TotalPoints, &i.ExamCount, &i.AvgPercentage)
	return i, err
}
