// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_questions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExamQuestion = `-- name: AddExamQuestion :one
INSERT INTO courses.exam_questions (
    exam_id, question_id, order_index, marks
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, exam_id, question_id, order_index, marks
`

type AddExamQuestionParams struct {
	ExamID     pgtype.UUID
	QuestionID pgtype.UUID
	OrderIndex int32
	Marks      int32
}

func (q *Queries) AddExamQuestion(ctx context.Context, arg AddExamQuestionParams) (CoursesExamQuestion, error) {
	row := q.db.QueryRow(ctx, addExamQuestion,
		arg.ExamID,
		arg.QuestionID,
		arg.OrderIndex,
		arg.Marks,
	)
	var i CoursesExamQuestion
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.QuestionID,
		&i.OrderIndex,
		&i.Marks,
	)
	return i, err
}

const listExamQuestions = `-- name: ListExamQuestions :many
SELECT id, exam_id, question_id, order_index, marks FROM courses.exam_questions
WHERE exam_id = $1
ORDER BY order_index ASC, id ASC
`

func (q *Queries) ListExamQuestions(ctx context.Context, examID pgtype.UUID) ([]CoursesExamQuestion, error) {
	rows, err := q.db.Query(ctx, listExamQuestions, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesExamQuestion{}
	for rows.Next() {
		var i CoursesExamQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.QuestionID,
			&i.OrderIndex,
			&i.Marks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamQuestionsForClient = `-- name: ListExamQuestionsForClient :many
SELECT
    eq.question_id  AS question_id,
    eq.order_index  AS order_index,
    eq.marks        AS marks,
    q.text          AS text,
    q.type          AS type,
    q.subject       AS subject,
    q.topic         AS topic
FROM courses.exam_questions eq
JOIN courses.questions q ON q.id = eq.question_id
WHERE eq.exam_id = $1
ORDER BY eq.order_index ASC, eq.id ASC
`

type ListExamQuestionsForClientRow struct {
	QuestionID pgtype.UUID
	OrderIndex int32
	Marks      int32
	Text       string
	Type       string
	Subject    *string
	Topic      *string
}

// ListExamQuestionsForClient renders the exam to the student: the per-exam order
// and marks joined to the question text/type, with NO is_correct anywhere in the
// projection (Non-Negotiable #1). Answer options come from ListAnswersForClient.
func (q *Queries) ListExamQuestionsForClient(ctx context.Context, examID pgtype.UUID) ([]ListExamQuestionsForClientRow, error) {
	rows, err := q.db.Query(ctx, listExamQuestionsForClient, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExamQuestionsForClientRow{}
	for rows.Next() {
		var i ListExamQuestionsForClientRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.OrderIndex,
			&i.Marks,
			&i.Text,
			&i.Type,
			&i.Subject,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamQuestionsForGrading = `-- name: ListExamQuestionsForGrading :many
SELECT
    eq.question_id  AS question_id,
    eq.marks        AS marks,
    q.type          AS type,
    q.subject       AS subject,
    q.topic         AS topic,
    a.id            AS answer_id,
    a.text          AS answer_text,
    a.is_correct    AS is_correct,
    a.order_index   AS answer_order_index
FROM courses.exam_questions eq
JOIN courses.questions q ON q.id = eq.question_id
JOIN courses.answers a ON a.question_id = q.id
WHERE eq.exam_id = $1
ORDER BY eq.order_index ASC, eq.id ASC, a.order_index ASC, a.id ASC
`

type ListExamQuestionsForGradingRow struct {
	QuestionID       pgtype.UUID
	Marks            int32
	Type             string
	Subject          *string
	Topic            *string
	AnswerID         pgtype.UUID
	AnswerText       string
	IsCorrect        bool
	AnswerOrderIndex int32
}

// ListExamQuestionsForGrading is server-side-only: per-exam marks joined to each
// answer option INCLUDING is_correct, for the shared grading core. Never map onto
// a client DTO.
func (q *Queries) ListExamQuestionsForGrading(ctx context.Context, examID pgtype.UUID) ([]ListExamQuestionsForGradingRow, error) {
	rows, err := q.db.Query(ctx, listExamQuestionsForGrading, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExamQuestionsForGradingRow{}
	for rows.Next() {
		var i ListExamQuestionsForGradingRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Marks,
			&i.Type,
			&i.Subject,
			&i.Topic,
			&i.AnswerID,
			&i.AnswerText,
			&i.IsCorrect,
			&i.AnswerOrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
