// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exams.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExam = `-- name: CreateExam :one
INSERT INTO courses.exams (
    course_id, title, subject, grade, duration_minutes, total_marks,
    pass_marks, instructions, is_published
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, course_id, title, subject, grade, duration_minutes, total_marks, pass_marks, instructions, is_published, created_at, updated_at, deleted_at
`

type CreateExamParams struct {
	CourseID        pgtype.UUID
	Title           string
	Subject         string
	Grade           int32
	DurationMinutes int32
	TotalMarks      int32
	PassMarks       int32
	Instructions    *string
	IsPublished     bool
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (CoursesExam, error) {
	row := q.db.QueryRow(ctx, createExam,
		arg.CourseID,
		arg.Title,
		arg.Subject,
		arg.Grade,
		arg.DurationMinutes,
		arg.TotalMarks,
		arg.PassMarks,
		arg.Instructions,
		arg.IsPublished,
	)
	var i CoursesExam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Subject,
		&i.Grade,
		&i.DurationMinutes,
		&i.TotalMarks,
		&i.PassMarks,
		&i.Instructions,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExamByID = `-- name: GetExamByID :one
SELECT id, course_id, title, subject, grade, duration_minutes, total_marks, pass_marks, instructions, is_published, created_at, updated_at, deleted_at FROM courses.exams
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetExamByID(ctx context.Context, id pgtype.UUID) (CoursesExam, error) {
	row := q.db.QueryRow(ctx, getExamByID, id)
	var i CoursesExam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Subject,
		&i.Grade,
		&i.DurationMinutes,
		&i.TotalMarks,
		&i.PassMarks,
		&i.Instructions,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExams = `-- name: ListExams :many
SELECT id, course_id, title, subject, grade, duration_minutes, total_marks, pass_marks, instructions, is_published, created_at, updated_at, deleted_at FROM courses.exams
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR subject = $1)
  AND ($2::int IS NULL OR grade = $2)
  AND ($3::bool IS NULL OR is_published = $3)
  AND (
      $4::timestamptz IS NULL
      OR (created_at, id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListExamsParams struct {
	Subject        *string
	Grade          *int32
	IsPublished    *bool
	AfterCreatedAt pgtype.Timestamptz
	AfterID        pgtype.UUID
	RowLimit       int32
}

// Keyset (cursor) pagination ordered by (created_at, id) DESC. Nullable filter
// args are ignored when NULL. Soft-deleted exams are excluded.
func (q *Queries) ListExams(ctx context.Context, arg ListExamsParams) ([]CoursesExam, error) {
	rows, err := q.db.Query(ctx, listExams,
		arg.Subject,
		arg.Grade,
		arg.IsPublished,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesExam{}
	for rows.Next() {
		var i CoursesExam
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Subject,
			&i.Grade,
			&i.DurationMinutes,
			&i.TotalMarks,
			&i.PassMarks,
			&i.Instructions,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExam = `-- name: SoftDeleteExam :exec
UPDATE courses.exams
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Non-Negotiable #5: tombstone, never physically DELETE.
func (q *Queries) SoftDeleteExam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteExam, id)
	return err
}

const updateExam = `-- name: UpdateExam :one
UPDATE courses.exams
SET title = $2,
    subject = $3,
    grade = $4,
    duration_minutes = $5,
    total_marks = $6,
    pass_marks = $7,
    instructions = $8,
    is_published = $9
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, course_id, title, subject, grade, duration_minutes, total_marks, pass_marks, instructions, is_published, created_at, updated_at, deleted_at
`

type UpdateExamParams struct {
	ID              pgtype.UUID
	Title           string
	Subject         string
	Grade           int32
	DurationMinutes int32
	TotalMarks      int32
	PassMarks       int32
	Instructions    *string
	IsPublished     bool
}

func (q *Queries) UpdateExam(ctx context.Context, arg UpdateExamParams) (CoursesExam, error) {
	row := q.db.QueryRow(ctx, updateExam,
		arg.ID,
		arg.Title,
		arg.Subject,
		arg.Grade,
		arg.DurationMinutes,
		arg.TotalMarks,
		arg.PassMarks,
		arg.Instructions,
		arg.IsPublished,
	)
	var i CoursesExam
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Subject,
		&i.Grade,
		&i.DurationMinutes,
		&i.TotalMarks,
		&i.PassMarks,
		&i.Instructions,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
