// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO courses.lessons (
    section_id, course_id, title, type, order_index, is_free_preview,
    duration_seconds, is_published, content, pdf_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, section_id, course_id, title, type, order_index, is_free_preview, duration_seconds, is_published, content, pdf_url, created_at, updated_at, deleted_at
`

type CreateLessonParams struct {
	SectionID       pgtype.UUID
	CourseID        pgtype.UUID
	Title           string
	Type            string
	OrderIndex      int32
	IsFreePreview   bool
	DurationSeconds int32
	IsPublished     bool
	Content         *string
	PdfUrl          *string
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (CoursesLesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.SectionID,
		arg.CourseID,
		arg.Title,
		arg.Type,
		arg.OrderIndex,
		arg.IsFreePreview,
		arg.DurationSeconds,
		arg.IsPublished,
		arg.Content,
		arg.PdfUrl,
	)
	var i CoursesLesson
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.CourseID,
		&i.Title,
		&i.Type,
		&i.OrderIndex,
		&i.IsFreePreview,
		&i.DurationSeconds,
		&i.IsPublished,
		&i.Content,
		&i.PdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT l.id, l.section_id, l.course_id, l.title, l.type, l.order_index, l.is_free_preview, l.duration_seconds, l.is_published, l.content, l.pdf_url, l.created_at, l.updated_at, l.deleted_at, v.id AS video_id
FROM courses.lessons l
LEFT JOIN courses.videos v ON v.lesson_id = l.id AND v.deleted_at IS NULL
WHERE l.id = $1 AND l.deleted_at IS NULL
`

type GetLessonByIDRow struct {
	ID              pgtype.UUID
	SectionID       pgtype.UUID
	CourseID        pgtype.UUID
	Title           string
	Type            string
	OrderIndex      int32
	IsFreePreview   bool
	DurationSeconds int32
	IsPublished     bool
	Content         *string
	PdfUrl          *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	VideoID         pgtype.UUID
}

func (q *Queries) GetLessonByID(ctx context.Context, id pgtype.UUID) (GetLessonByIDRow, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i GetLessonByIDRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.CourseID,
		&i.Title,
		&i.Type,
		&i.OrderIndex,
		&i.IsFreePreview,
		&i.DurationSeconds,
		&i.IsPublished,
		&i.Content,
		&i.PdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VideoID,
	)
	return i, err
}

const listLessonsByCourse = `-- name: ListLessonsByCourse :many
SELECT l.id, l.section_id, l.course_id, l.title, l.type, l.order_index, l.is_free_preview, l.duration_seconds, l.is_published, l.content, l.pdf_url, l.created_at, l.updated_at, l.deleted_at, v.id AS video_id
FROM courses.lessons l
LEFT JOIN courses.videos v ON v.lesson_id = l.id AND v.deleted_at IS NULL
WHERE l.course_id = $1 AND l.deleted_at IS NULL
ORDER BY l.order_index ASC, l.created_at ASC
`

type ListLessonsByCourseRow struct {
	ID              pgtype.UUID
	SectionID       pgtype.UUID
	CourseID        pgtype.UUID
	Title           string
	Type            string
	OrderIndex      int32
	IsFreePreview   bool
	DurationSeconds int32
	IsPublished     bool
	Content         *string
	PdfUrl          *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	VideoID         pgtype.UUID
}

func (q *Queries) ListLessonsByCourse(ctx context.Context, courseID pgtype.UUID) ([]ListLessonsByCourseRow, error) {
	rows, err := q.db.Query(ctx, listLessonsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLessonsByCourseRow{}
	for rows.Next() {
		var i ListLessonsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.CourseID,
			&i.Title,
			&i.Type,
			&i.OrderIndex,
			&i.IsFreePreview,
			&i.DurationSeconds,
			&i.IsPublished,
			&i.Content,
			&i.PdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.VideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsBySection = `-- name: ListLessonsBySection :many
SELECT l.id, l.section_id, l.course_id, l.title, l.type, l.order_index, l.is_free_preview, l.duration_seconds, l.is_published, l.content, l.pdf_url, l.created_at, l.updated_at, l.deleted_at, v.id AS video_id
FROM courses.lessons l
LEFT JOIN courses.videos v ON v.lesson_id = l.id AND v.deleted_at IS NULL
WHERE l.section_id = $1 AND l.deleted_at IS NULL
ORDER BY l.order_index ASC, l.created_at ASC
`

type ListLessonsBySectionRow struct {
	ID              pgtype.UUID
	SectionID       pgtype.UUID
	CourseID        pgtype.UUID
	Title           string
	Type            string
	OrderIndex      int32
	IsFreePreview   bool
	DurationSeconds int32
	IsPublished     bool
	Content         *string
	PdfUrl          *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	VideoID         pgtype.UUID
}

func (q *Queries) ListLessonsBySection(ctx context.Context, sectionID pgtype.UUID) ([]ListLessonsBySectionRow, error) {
	rows, err := q.db.Query(ctx, listLessonsBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLessonsBySectionRow{}
	for rows.Next() {
		var i ListLessonsBySectionRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.CourseID,
			&i.Title,
			&i.Type,
			&i.OrderIndex,
			&i.IsFreePreview,
			&i.DurationSeconds,
			&i.IsPublished,
			&i.Content,
			&i.PdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.VideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxLessonOrderIndex = `-- name: MaxLessonOrderIndex :one
SELECT COALESCE(MAX(order_index), -1)::int AS max_order_index
FROM courses.lessons
WHERE section_id = $1 AND deleted_at IS NULL
`

// Highest order_index among a section's live lessons; -1 when none exist.
func (q *Queries) MaxLessonOrderIndex(ctx context.Context, sectionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxLessonOrderIndex, sectionID)
	var max_order_index int32
	err := row.Scan(&max_order_index)
	return max_order_index, err
}

const softDeleteLesson = `-- name: SoftDeleteLesson :exec
UPDATE courses.lessons
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLesson(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteLesson, id)
	return err
}

const softDeleteLessonsBySection = `-- name: SoftDeleteLessonsBySection :exec
UPDATE courses.lessons
SET deleted_at = now()
WHERE section_id = $1 AND deleted_at IS NULL
`

// Cascade soft-delete: when a section is removed, tombstone its live lessons too.
func (q *Queries) SoftDeleteLessonsBySection(ctx context.Context, sectionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteLessonsBySection, sectionID)
	return err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE courses.lessons
SET title = $2,
    type = $3,
    order_index = $4,
    is_free_preview = $5,
    duration_seconds = $6,
    is_published = $7,
    content = COALESCE($8, content),
    pdf_url = COALESCE($9, pdf_url)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, section_id, course_id, title, type, order_index, is_free_preview, duration_seconds, is_published, content, pdf_url, created_at, updated_at, deleted_at
`

type UpdateLessonParams struct {
	ID              pgtype.UUID
	Title           string
	Type            string
	OrderIndex      int32
	IsFreePreview   bool
	DurationSeconds int32
	IsPublished     bool
	Content         *string
	PdfUrl          *string
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (CoursesLesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.OrderIndex,
		arg.IsFreePreview,
		arg.DurationSeconds,
		arg.IsPublished,
		arg.Content,
		arg.PdfUrl,
	)
	var i CoursesLesson
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.CourseID,
		&i.Title,
		&i.Type,
		&i.OrderIndex,
		&i.IsFreePreview,
		&i.DurationSeconds,
		&i.IsPublished,
		&i.Content,
		&i.PdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
