// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthRefreshToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	DeviceInfo *string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type AuthUser struct {
	ID                     pgtype.UUID
	Email                  string
	Phone                  *string
	PasswordHash           string
	Role                   string
	FirstName              string
	LastName               string
	AvatarUrl              *string
	IsActive               bool
	IsEmailVerified        bool
	EmailVerificationToken *string
	PasswordResetToken     *string
	PasswordResetExpiresAt pgtype.Timestamptz
	LastLoginAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type CoursesAnswer struct {
	ID         pgtype.UUID
	QuestionID pgtype.UUID
	Text       string
	IsCorrect  bool
	OrderIndex int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type CoursesCourse struct {
	ID                   pgtype.UUID
	TeacherID            pgtype.UUID
	Title                string
	Slug                 string
	Description          string
	ShortDescription     *string
	Subject              string
	Grade                int32
	ThumbnailUrl         *string
	Price                pgtype.Numeric
	Currency             string
	IsFree               bool
	IsPublished          bool
	Language             string
	Level                string
	TotalDurationSeconds int32
	TotalLessons         int32
	RatingAvg            pgtype.Numeric
	EnrollmentCount      int32
	Metadata             []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type CoursesCourseSection struct {
	ID          pgtype.UUID
	CourseID    pgtype.UUID
	Title       string
	Description *string
	OrderIndex  int32
	IsPublished bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type CoursesExam struct {
	ID              pgtype.UUID
	CourseID        pgtype.UUID
	Title           string
	Subject         string
	Grade           int32
	DurationMinutes int32
	TotalMarks      int32
	PassMarks       int32
	Instructions    *string
	IsPublished     bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type CoursesExamAttempt struct {
	ID              pgtype.UUID
	ExamID          pgtype.UUID
	StudentID       pgtype.UUID
	StartedAt       pgtype.Timestamptz
	SubmittedAt     pgtype.Timestamptz
	Score           pgtype.Numeric
	Percentage      pgtype.Numeric
	AnswersSnapshot []byte
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CoursesExamQuestion struct {
	ID         pgtype.UUID
	ExamID     pgtype.UUID
	QuestionID pgtype.UUID
	OrderIndex int32
	Marks      int32
}

type CoursesLesson struct {
	ID              pgtype.UUID
	SectionID       pgtype.UUID
	CourseID        pgtype.UUID
	Title           string
	Type            string
	OrderIndex      int32
	IsFreePreview   bool
	DurationSeconds int32
	IsPublished     bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type CoursesQuestion struct {
	ID          pgtype.UUID
	QuizID      pgtype.UUID
	Text        string
	Type        string
	Points      int32
	Explanation *string
	OrderIndex  int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Subject     *string
	Topic       *string
}

type CoursesQuiz struct {
	ID                 pgtype.UUID
	LessonID           pgtype.UUID
	CourseID           pgtype.UUID
	Title              string
	TimeLimitSeconds   *int32
	PassPercentage     pgtype.Numeric
	RandomizeQuestions bool
	MaxAttempts        *int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type CoursesQuizAttempt struct {
	ID              pgtype.UUID
	QuizID          pgtype.UUID
	StudentID       pgtype.UUID
	AttemptNumber   int32
	StartedAt       pgtype.Timestamptz
	SubmittedAt     pgtype.Timestamptz
	Score           pgtype.Numeric
	Percentage      pgtype.Numeric
	AnswersSnapshot []byte
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	QuestionOrder   []byte
	ExpiresAt       pgtype.Timestamptz
	Passed          *bool
}

type CoursesVideo struct {
	ID                 pgtype.UUID
	LessonID           pgtype.UUID
	OriginalFileKey    *string
	HlsMasterKey       *string
	ProcessingStatus   string
	DurationSeconds    int32
	Resolution480pKey  *string
	Resolution720pKey  *string
	Resolution1080pKey *string
	ThumbnailKey       *string
	FileSizeBytes      int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CourseID           pgtype.UUID
	ProcessingError    *string
	ProcessedAt        pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type PaymentsCoupon struct {
	ID            pgtype.UUID
	Code          string
	DiscountType  string
	DiscountValue pgtype.Numeric
	MaxUses       *int32
	UsedCount     int32
	ExpiresAt     pgtype.Timestamptz
	ApplicableTo  string
	CourseIds     []pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PaymentsEnrollment struct {
	ID         pgtype.UUID
	StudentID  pgtype.UUID
	CourseID   pgtype.UUID
	EnrolledAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	Source     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type PaymentsPayment struct {
	ID                    pgtype.UUID
	StudentID             pgtype.UUID
	CourseID              pgtype.UUID
	Amount                pgtype.Numeric
	Currency              string
	Provider              string
	ProviderTransactionID *string
	Status                string
	CouponID              pgtype.UUID
	IdempotencyKey        string
	Metadata              []byte
	PaidAt                pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ProviderCheckoutID    *string
	SubscriptionID        pgtype.UUID
	FailureReason         *string
}

type PaymentsSubscription struct {
	ID                     pgtype.UUID
	StudentID              pgtype.UUID
	Plan                   string
	Status                 string
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	Provider               string
	ProviderSubscriptionID *string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	CanceledAt             pgtype.Timestamptz
}

type PaymentsWebhookEvent struct {
	ID              pgtype.UUID
	Provider        string
	ProviderEventID string
	EventType       string
	Payload         []byte
	ProcessedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type ProgressProgress struct {
	ID                   pgtype.UUID
	StudentID            pgtype.UUID
	LessonID             pgtype.UUID
	CourseID             pgtype.UUID
	IsCompleted          bool
	CompletedAt          pgtype.Timestamptz
	VideoProgressSeconds int32
	LastAccessedAt       pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type ProgressCourseProgress struct {
	StudentID        pgtype.UUID
	CourseID         pgtype.UUID
	CompletedLessons int32
	TotalLessons     int32
	PercentComplete  pgtype.Numeric
	CompletedAt      pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ProgressStudyStreak struct {
	StudentID      pgtype.UUID
	CurrentStreak  int32
	LongestStreak  int32
	LastStudyDate  pgtype.Date
	LastWarnedDate pgtype.Date
	UpdatedAt      pgtype.Timestamptz
}

type NotificationsNotification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Title     string
	Body      string
	Data      []byte // JSONB scanned as raw bytes
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type NotificationsDeviceToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	FCMToken  string
	Platform  string
	CreatedAt pgtype.Timestamptz
}

type NotificationsPreference struct {
	UserID       pgtype.UUID
	PushEnabled  bool
	EmailEnabled bool
	UpdatedAt    pgtype.Timestamptz
}
