// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications.notifications (user_id, type, title, body, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, data, read_at, created_at
`

type CreateNotificationParams struct {
	UserID pgtype.UUID
	Type   string
	Title  string
	Body   string
	Data   []byte
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (NotificationsNotification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i NotificationsNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, body, data, read_at, created_at
FROM notifications.notifications
WHERE user_id = $1
ORDER BY read_at NULLS FIRST, created_at DESC
LIMIT $2
`

func (q *Queries) ListNotificationsByUser(ctx context.Context, userID pgtype.UUID, limit int32) ([]NotificationsNotification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, userID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationsNotification
	for rows.Next() {
		var i NotificationsNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, type, title, body, data, read_at, created_at
FROM notifications.notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (NotificationsNotification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i NotificationsNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications.notifications
SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id, userID)
	return err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications.notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const unreadNotificationCount = `-- name: UnreadNotificationCount :one
SELECT COUNT(*)::int AS count
FROM notifications.notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) UnreadNotificationCount(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, unreadNotificationCount, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO notifications.device_tokens (user_id, fcm_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (fcm_token) DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform
`

type UpsertDeviceTokenParams struct {
	UserID   pgtype.UUID
	FCMToken string
	Platform string
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken, arg.UserID, arg.FCMToken, arg.Platform)
	return err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM notifications.device_tokens WHERE fcm_token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, fcmToken)
	return err
}

const deleteInvalidDeviceTokens = `-- name: DeleteInvalidDeviceTokens :exec
DELETE FROM notifications.device_tokens WHERE fcm_token = ANY($1::text[])
`

func (q *Queries) DeleteInvalidDeviceTokens(ctx context.Context, tokens []string) error {
	_, err := q.db.Exec(ctx, deleteInvalidDeviceTokens, tokens)
	return err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, fcm_token, platform, created_at
FROM notifications.device_tokens
WHERE user_id = $1
`

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID pgtype.UUID) ([]NotificationsDeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationsDeviceToken
	for rows.Next() {
		var i NotificationsDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FCMToken,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, push_enabled, email_enabled, updated_at
FROM notifications.preferences
WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationsPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationsPreference
	err := row.Scan(&i.UserID, &i.PushEnabled, &i.EmailEnabled, &i.UpdatedAt)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :exec
INSERT INTO notifications.preferences (user_id, push_enabled, email_enabled, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE SET
    push_enabled  = EXCLUDED.push_enabled,
    email_enabled = EXCLUDED.email_enabled,
    updated_at    = now()
`

type UpsertNotificationPreferencesParams struct {
	UserID       pgtype.UUID
	PushEnabled  bool
	EmailEnabled bool
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreferences, arg.UserID, arg.PushEnabled, arg.EmailEnabled)
	return err
}
