// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments.payments (
    id, student_id, course_id, subscription_id, amount, currency,
    provider, provider_checkout_id, status, coupon_id, idempotency_key, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, student_id, course_id, amount, currency, provider, provider_transaction_id, status, coupon_id, idempotency_key, metadata, paid_at, created_at, updated_at, provider_checkout_id, subscription_id, failure_reason
`

type CreatePaymentParams struct {
	ID                 pgtype.UUID
	StudentID          pgtype.UUID
	CourseID           pgtype.UUID
	SubscriptionID     pgtype.UUID
	Amount             pgtype.Numeric
	Currency           string
	Provider           string
	ProviderCheckoutID *string
	Status             string
	CouponID           pgtype.UUID
	IdempotencyKey     string
	Metadata           []byte
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.StudentID,
		arg.CourseID,
		arg.SubscriptionID,
		arg.Amount,
		arg.Currency,
		arg.Provider,
		arg.ProviderCheckoutID,
		arg.Status,
		arg.CouponID,
		arg.IdempotencyKey,
		arg.Metadata,
	)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderCheckoutID,
		&i.SubscriptionID,
		&i.FailureReason,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, student_id, course_id, amount, currency, provider, provider_transaction_id, status, coupon_id, idempotency_key, metadata, paid_at, created_at, updated_at, provider_checkout_id, subscription_id, failure_reason FROM payments.payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderCheckoutID,
		&i.SubscriptionID,
		&i.FailureReason,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, student_id, course_id, amount, currency, provider, provider_transaction_id, status, coupon_id, idempotency_key, metadata, paid_at, created_at, updated_at, provider_checkout_id, subscription_id, failure_reason FROM payments.payments WHERE idempotency_key = $1
`

// GetPaymentByIdempotencyKey is the friendly idempotency path: a retried initiate
// with the same client key returns the existing payment instead of charging again.
func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderCheckoutID,
		&i.SubscriptionID,
		&i.FailureReason,
	)
	return i, err
}

const getPaymentByProviderTxn = `-- name: GetPaymentByProviderTxn :one
SELECT id, student_id, course_id, amount, currency, provider, provider_transaction_id, status, coupon_id, idempotency_key, metadata, paid_at, created_at, updated_at, provider_checkout_id, subscription_id, failure_reason FROM payments.payments
WHERE provider = $1 AND provider_transaction_id = $2
`

type GetPaymentByProviderTxnParams struct {
	Provider              string
	ProviderTransactionID *string
}

func (q *Queries) GetPaymentByProviderTxn(ctx context.Context, arg GetPaymentByProviderTxnParams) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderTxn, arg.Provider, arg.ProviderTransactionID)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderCheckoutID,
		&i.SubscriptionID,
		&i.FailureReason,
	)
	return i, err
}

const listPaymentsByStudent = `-- name: ListPaymentsByStudent :many
SELECT id, student_id, course_id, amount, currency, provider, provider_transaction_id, status, coupon_id, idempotency_key, metadata, paid_at, created_at, updated_at, provider_checkout_id, subscription_id, failure_reason FROM payments.payments
WHERE student_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPaymentsByStudentParams struct {
	StudentID pgtype.UUID
	Limit     int32
}

func (q *Queries) ListPaymentsByStudent(ctx context.Context, arg ListPaymentsByStudentParams) ([]PaymentsPayment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByStudent, arg.StudentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsPayment{}
	for rows.Next() {
		var i PaymentsPayment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CourseID,
			&i.Amount,
			&i.Currency,
			&i.Provider,
			&i.ProviderTransactionID,
			&i.Status,
			&i.CouponID,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderCheckoutID,
			&i.SubscriptionID,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatusGuarded = `-- name: UpdatePaymentStatusGuarded :execrows
UPDATE payments.payments
SET status = $1,
    provider_transaction_id = COALESCE($2, provider_transaction_id),
    failure_reason = COALESCE($3, failure_reason),
    paid_at = CASE WHEN $4::boolean THEN now() ELSE paid_at END,
    updated_at = now()
WHERE id = $5 AND status = $6
`

type UpdatePaymentStatusGuardedParams struct {
	ToStatus      string
	ProviderTxn   *string
	FailureReason *string
	SetPaid       bool
	ID            pgtype.UUID
	FromStatus    string
}

// UpdatePaymentStatusGuarded flips status only when the row still holds
// from_status; :execrows lets the repo report changed=false (0 rows) without an
// error so a re-delivered webhook cannot double-settle an already-settled payment.
// paid_at is stamped only on the transition to completed.
func (q *Queries) UpdatePaymentStatusGuarded(ctx context.Context, arg UpdatePaymentStatusGuardedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentStatusGuarded,
		arg.ToStatus,
		arg.ProviderTxn,
		arg.FailureReason,
		arg.SetPaid,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
