// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO progress.progress (
    id, student_id, lesson_id, course_id, is_completed,
    completed_at, video_progress_seconds, last_accessed_at
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4,
    CASE WHEN $4 THEN now() ELSE NULL END,
    $5, now()
)
ON CONFLICT (student_id, lesson_id) WHERE deleted_at IS NULL
DO UPDATE SET
    is_completed           = EXCLUDED.is_completed OR progress.progress.is_completed,
    completed_at           = COALESCE(progress.progress.completed_at, EXCLUDED.completed_at),
    video_progress_seconds = GREATEST(progress.progress.video_progress_seconds, EXCLUDED.video_progress_seconds),
    last_accessed_at       = now(),
    updated_at             = now()
RETURNING id, student_id, lesson_id, course_id, is_completed, completed_at, video_progress_seconds, last_accessed_at, created_at, updated_at, deleted_at
`

type UpsertLessonProgressParams struct {
	StudentID            pgtype.UUID
	LessonID             pgtype.UUID
	CourseID             pgtype.UUID
	IsCompleted          bool
	VideoProgressSeconds int32
}

func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (ProgressProgress, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress,
		arg.StudentID,
		arg.LessonID,
		arg.CourseID,
		arg.IsCompleted,
		arg.VideoProgressSeconds,
	)
	var i ProgressProgress
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.LessonID,
		&i.CourseID,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.VideoProgressSeconds,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT id, student_id, lesson_id, course_id, is_completed, completed_at, video_progress_seconds, last_accessed_at, created_at, updated_at, deleted_at FROM progress.progress
WHERE student_id = $1 AND lesson_id = $2 AND deleted_at IS NULL
`

func (q *Queries) GetLessonProgress(ctx context.Context, studentID pgtype.UUID, lessonID pgtype.UUID) (ProgressProgress, error) {
	row := q.db.QueryRow(ctx, getLessonProgress, studentID, lessonID)
	var i ProgressProgress
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.LessonID,
		&i.CourseID,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.VideoProgressSeconds,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listByCourse = `-- name: ListByCourse :many
SELECT id, student_id, lesson_id, course_id, is_completed, completed_at, video_progress_seconds, last_accessed_at, created_at, updated_at, deleted_at FROM progress.progress
WHERE student_id = $1 AND course_id = $2 AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListByCourse(ctx context.Context, studentID pgtype.UUID, courseID pgtype.UUID) ([]ProgressProgress, error) {
	rows, err := q.db.Query(ctx, listByCourse, studentID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgressProgress
	for rows.Next() {
		var i ProgressProgress
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.LessonID,
			&i.CourseID,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.VideoProgressSeconds,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countCourseCompletion = `-- name: CountCourseCompletion :one
SELECT
    (SELECT COUNT(*)::int
     FROM courses.lessons l
     WHERE l.course_id = $2 AND l.deleted_at IS NULL AND l.is_published) AS total,
    (SELECT COUNT(*)::int
     FROM progress.progress p
     WHERE p.student_id = $1 AND p.course_id = $2
       AND p.is_completed AND p.deleted_at IS NULL) AS completed
`

type CountCourseCompletionRow struct {
	Total     int32
	Completed int32
}

func (q *Queries) CountCourseCompletion(ctx context.Context, studentID pgtype.UUID, courseID pgtype.UUID) (CountCourseCompletionRow, error) {
	row := q.db.QueryRow(ctx, countCourseCompletion, studentID, courseID)
	var i CountCourseCompletionRow
	err := row.Scan(&i.Total, &i.Completed)
	return i, err
}

const upsertCourseProgress = `-- name: UpsertCourseProgress :exec
INSERT INTO progress.course_progress (
    student_id, course_id, completed_lessons, total_lessons,
    percent_complete, completed_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (student_id, course_id)
DO UPDATE SET
    completed_lessons = EXCLUDED.completed_lessons,
    total_lessons     = EXCLUDED.total_lessons,
    percent_complete  = EXCLUDED.percent_complete,
    completed_at      = COALESCE(progress.course_progress.completed_at, EXCLUDED.completed_at),
    updated_at        = now()
`

type UpsertCourseProgressParams struct {
	StudentID        pgtype.UUID
	CourseID         pgtype.UUID
	CompletedLessons int32
	TotalLessons     int32
	PercentComplete  pgtype.Numeric
	CompletedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertCourseProgress(ctx context.Context, arg UpsertCourseProgressParams) error {
	_, err := q.db.Exec(ctx, upsertCourseProgress,
		arg.StudentID,
		arg.CourseID,
		arg.CompletedLessons,
		arg.TotalLessons,
		arg.PercentComplete,
		arg.CompletedAt,
	)
	return err
}

const getCourseProgress = `-- name: GetCourseProgress :one
SELECT student_id, course_id, completed_lessons, total_lessons, percent_complete, completed_at, updated_at FROM progress.course_progress
WHERE student_id = $1 AND course_id = $2
`

func (q *Queries) GetCourseProgress(ctx context.Context, studentID pgtype.UUID, courseID pgtype.UUID) (ProgressCourseProgress, error) {
	row := q.db.QueryRow(ctx, getCourseProgress, studentID, courseID)
	var i ProgressCourseProgress
	err := row.Scan(
		&i.StudentID,
		&i.CourseID,
		&i.CompletedLessons,
		&i.TotalLessons,
		&i.PercentComplete,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStreak = `-- name: GetStreak :one
SELECT student_id, current_streak, longest_streak, last_study_date, updated_at FROM progress.study_streaks WHERE student_id = $1
`

func (q *Queries) GetStreak(ctx context.Context, studentID pgtype.UUID) (ProgressStudyStreak, error) {
	row := q.db.QueryRow(ctx, getStreak, studentID)
	var i ProgressStudyStreak
	err := row.Scan(
		&i.StudentID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastStudyDate,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStreak = `-- name: UpsertStreak :exec
INSERT INTO progress.study_streaks (
    student_id, current_streak, longest_streak, last_study_date, updated_at
)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (student_id)
DO UPDATE SET
    current_streak  = EXCLUDED.current_streak,
    longest_streak  = EXCLUDED.longest_streak,
    last_study_date = EXCLUDED.last_study_date,
    updated_at      = now()
`

type UpsertStreakParams struct {
	StudentID      pgtype.UUID
	CurrentStreak  int32
	LongestStreak  int32
	LastStudyDate  pgtype.Date
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) error {
	_, err := q.db.Exec(ctx, upsertStreak,
		arg.StudentID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastStudyDate,
	)
	return err
}

const listStreakAtRisk = `-- name: ListStreakAtRisk :many
SELECT student_id, current_streak, longest_streak, last_study_date, last_warned_date, updated_at
FROM progress.study_streaks
WHERE current_streak > 0
  AND last_study_date < $1
  AND (last_warned_date IS NULL OR last_warned_date < $2)
ORDER BY student_id
LIMIT $3
`

type ListStreakAtRiskParams struct {
	Cutoff  pgtype.Date
	Today   pgtype.Date
	Limit   int32
}

func (q *Queries) ListStreakAtRisk(ctx context.Context, arg ListStreakAtRiskParams) ([]ProgressStudyStreak, error) {
	rows, err := q.db.Query(ctx, listStreakAtRisk, arg.Cutoff, arg.Today, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgressStudyStreak
	for rows.Next() {
		var i ProgressStudyStreak
		if err := rows.Scan(
			&i.StudentID,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.LastStudyDate,
			&i.LastWarnedDate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const setLastWarnedDate = `-- name: SetLastWarnedDate :exec
UPDATE progress.study_streaks SET last_warned_date = $2, updated_at = now() WHERE student_id = $1
`

func (q *Queries) SetLastWarnedDate(ctx context.Context, studentID pgtype.UUID, date pgtype.Date) error {
	_, err := q.db.Exec(ctx, setLastWarnedDate, studentID, date)
	return err
}
