// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO courses.questions (
    quiz_id, text, type, points, explanation, order_index, subject, topic
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, quiz_id, text, type, points, explanation, order_index, created_at, updated_at, subject, topic
`

type CreateQuestionParams struct {
	QuizID      pgtype.UUID
	Text        string
	Type        string
	Points      int32
	Explanation *string
	OrderIndex  int32
	Subject     *string
	Topic       *string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (CoursesQuestion, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.QuizID,
		arg.Text,
		arg.Type,
		arg.Points,
		arg.Explanation,
		arg.OrderIndex,
		arg.Subject,
		arg.Topic,
	)
	var i CoursesQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Type,
		&i.Points,
		&i.Explanation,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.Topic,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM courses.questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, quiz_id, text, type, points, explanation, order_index, created_at, updated_at, subject, topic FROM courses.questions
WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id pgtype.UUID) (CoursesQuestion, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i CoursesQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Type,
		&i.Points,
		&i.Explanation,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.Topic,
	)
	return i, err
}

const getQuestionsForClient = `-- name: GetQuestionsForClient :many
SELECT id, quiz_id, text, type, points, order_index, subject, topic
FROM courses.questions
WHERE quiz_id = $1
ORDER BY order_index ASC, id ASC
`

type GetQuestionsForClientRow struct {
	ID         pgtype.UUID
	QuizID     pgtype.UUID
	Text       string
	Type       string
	Points     int32
	OrderIndex int32
	Subject    *string
	Topic      *string
}

// GetQuestionsForClient renders the attempt to the student. It selects ONLY the
// non-secret columns — there is no is_correct anywhere in the projection, so the
// generated row struct structurally cannot carry the answer key (Non-Negotiable
// #1). Answer options for these questions are fetched via ListAnswersForClient.
func (q *Queries) GetQuestionsForClient(ctx context.Context, quizID pgtype.UUID) ([]GetQuestionsForClientRow, error) {
	rows, err := q.db.Query(ctx, getQuestionsForClient, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetQuestionsForClientRow{}
	for rows.Next() {
		var i GetQuestionsForClientRow
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Text,
			&i.Type,
			&i.Points,
			&i.OrderIndex,
			&i.Subject,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsForGrading = `-- name: GetQuestionsForGrading :many
SELECT
    q.id          AS question_id,
    q.points      AS points,
    q.type        AS type,
    a.id          AS answer_id,
    a.text        AS answer_text,
    a.is_correct  AS is_correct,
    a.order_index AS answer_order_index
FROM courses.questions q
JOIN courses.answers a ON a.question_id = q.id
WHERE q.quiz_id = $1
ORDER BY q.order_index ASC, q.id ASC, a.order_index ASC, a.id ASC
`

type GetQuestionsForGradingRow struct {
	QuestionID       pgtype.UUID
	Points           int32
	Type             string
	AnswerID         pgtype.UUID
	AnswerText       string
	IsCorrect        bool
	AnswerOrderIndex int32
}

// GetQuestionsForGrading is the server-side-only counterpart: it returns each
// question joined to its answer options INCLUDING is_correct, for the grading
// core. This result must never be mapped onto a client DTO.
func (q *Queries) GetQuestionsForGrading(ctx context.Context, quizID pgtype.UUID) ([]GetQuestionsForGradingRow, error) {
	rows, err := q.db.Query(ctx, getQuestionsForGrading, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetQuestionsForGradingRow{}
	for rows.Next() {
		var i GetQuestionsForGradingRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Points,
			&i.Type,
			&i.AnswerID,
			&i.AnswerText,
			&i.IsCorrect,
			&i.AnswerOrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByQuiz = `-- name: ListQuestionsByQuiz :many
SELECT id, quiz_id, text, type, points, explanation, order_index, created_at, updated_at, subject, topic FROM courses.questions
WHERE quiz_id = $1
ORDER BY order_index ASC, id ASC
`

func (q *Queries) ListQuestionsByQuiz(ctx context.Context, quizID pgtype.UUID) ([]CoursesQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestionsByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesQuestion{}
	for rows.Next() {
		var i CoursesQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Text,
			&i.Type,
			&i.Points,
			&i.Explanation,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE courses.questions
SET text = $2,
    type = $3,
    points = $4,
    explanation = $5,
    order_index = $6,
    subject = $7,
    topic = $8
WHERE id = $1
RETURNING id, quiz_id, text, type, points, explanation, order_index, created_at, updated_at, subject, topic
`

type UpdateQuestionParams struct {
	ID          pgtype.UUID
	Text        string
	Type        string
	Points      int32
	Explanation *string
	OrderIndex  int32
	Subject     *string
	Topic       *string
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (CoursesQuestion, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Text,
		arg.Type,
		arg.Points,
		arg.Explanation,
		arg.OrderIndex,
		arg.Subject,
		arg.Topic,
	)
	var i CoursesQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Type,
		&i.Points,
		&i.Explanation,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.Topic,
	)
	return i, err
}
