// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO courses.quizzes (
    lesson_id, course_id, title, time_limit_seconds, pass_percentage,
    randomize_questions, max_attempts
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, lesson_id, course_id, title, time_limit_seconds, pass_percentage, randomize_questions, max_attempts, created_at, updated_at, deleted_at
`

type CreateQuizParams struct {
	LessonID           pgtype.UUID
	CourseID           pgtype.UUID
	Title              string
	TimeLimitSeconds   *int32
	PassPercentage     pgtype.Numeric
	RandomizeQuestions bool
	MaxAttempts        *int32
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (CoursesQuiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.LessonID,
		arg.CourseID,
		arg.Title,
		arg.TimeLimitSeconds,
		arg.PassPercentage,
		arg.RandomizeQuestions,
		arg.MaxAttempts,
	)
	var i CoursesQuiz
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.CourseID,
		&i.Title,
		&i.TimeLimitSeconds,
		&i.PassPercentage,
		&i.RandomizeQuestions,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT id, lesson_id, course_id, title, time_limit_seconds, pass_percentage, randomize_questions, max_attempts, created_at, updated_at, deleted_at FROM courses.quizzes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetQuizByID(ctx context.Context, id pgtype.UUID) (CoursesQuiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i CoursesQuiz
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.CourseID,
		&i.Title,
		&i.TimeLimitSeconds,
		&i.PassPercentage,
		&i.RandomizeQuestions,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listQuizzesByCourse = `-- name: ListQuizzesByCourse :many
SELECT id, lesson_id, course_id, title, time_limit_seconds, pass_percentage, randomize_questions, max_attempts, created_at, updated_at, deleted_at FROM courses.quizzes
WHERE course_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListQuizzesByCourse(ctx context.Context, courseID pgtype.UUID) ([]CoursesQuiz, error) {
	rows, err := q.db.Query(ctx, listQuizzesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesQuiz{}
	for rows.Next() {
		var i CoursesQuiz
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.CourseID,
			&i.Title,
			&i.TimeLimitSeconds,
			&i.PassPercentage,
			&i.RandomizeQuestions,
			&i.MaxAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteQuiz = `-- name: SoftDeleteQuiz :exec
UPDATE courses.quizzes
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Non-Negotiable #5: tombstone, never physically DELETE. Attempts referencing
// the quiz are preserved as historical records.
func (q *Queries) SoftDeleteQuiz(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteQuiz, id)
	return err
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE courses.quizzes
SET title = $2,
    time_limit_seconds = $3,
    pass_percentage = $4,
    randomize_questions = $5,
    max_attempts = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, lesson_id, course_id, title, time_limit_seconds, pass_percentage, randomize_questions, max_attempts, created_at, updated_at, deleted_at
`

type UpdateQuizParams struct {
	ID                 pgtype.UUID
	Title              string
	TimeLimitSeconds   *int32
	PassPercentage     pgtype.Numeric
	RandomizeQuestions bool
	MaxAttempts        *int32
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (CoursesQuiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.ID,
		arg.Title,
		arg.TimeLimitSeconds,
		arg.PassPercentage,
		arg.RandomizeQuestions,
		arg.MaxAttempts,
	)
	var i CoursesQuiz
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.CourseID,
		&i.Title,
		&i.TimeLimitSeconds,
		&i.PassPercentage,
		&i.RandomizeQuestions,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
