// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_attempts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimQuizAttemptForGrading = `-- name: ClaimQuizAttemptForGrading :one
UPDATE courses.quiz_attempts
SET status = $2,
    answers_snapshot = $3,
    submitted_at = $4
WHERE id = $1 AND status = 'in_progress'
RETURNING id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed
`

type ClaimQuizAttemptForGradingParams struct {
	ID              pgtype.UUID
	Status          string
	AnswersSnapshot []byte
	SubmittedAt     pgtype.Timestamptz
}

// Race-safe transition out of in_progress (Non-Negotiable #2 server timer): the
// WHERE status='in_progress' predicate means only the first writer (a late client
// submit OR the background sweeper) flips the row; the loser matches no row and
// no-ops. $2 is the target status ('submitted' or 'expired').
func (q *Queries) ClaimQuizAttemptForGrading(ctx context.Context, arg ClaimQuizAttemptForGradingParams) (CoursesQuizAttempt, error) {
	row := q.db.QueryRow(ctx, claimQuizAttemptForGrading,
		arg.ID,
		arg.Status,
		arg.AnswersSnapshot,
		arg.SubmittedAt,
	)
	var i CoursesQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionOrder,
		&i.ExpiresAt,
		&i.Passed,
	)
	return i, err
}

const countQuizAttempts = `-- name: CountQuizAttempts :one
SELECT count(*) FROM courses.quiz_attempts
WHERE student_id = $1 AND quiz_id = $2
`

type CountQuizAttemptsParams struct {
	StudentID pgtype.UUID
	QuizID    pgtype.UUID
}

func (q *Queries) CountQuizAttempts(ctx context.Context, arg CountQuizAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuizAttempts, arg.StudentID, arg.QuizID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuizAttempt = `-- name: CreateQuizAttempt :one
INSERT INTO courses.quiz_attempts (
    quiz_id, student_id, attempt_number, expires_at, question_order,
    answers_snapshot, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed
`

type CreateQuizAttemptParams struct {
	QuizID          pgtype.UUID
	StudentID       pgtype.UUID
	AttemptNumber   int32
	ExpiresAt       pgtype.Timestamptz
	QuestionOrder   []byte
	AnswersSnapshot []byte
	Status          string
}

func (q *Queries) CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (CoursesQuizAttempt, error) {
	row := q.db.QueryRow(ctx, createQuizAttempt,
		arg.QuizID,
		arg.StudentID,
		arg.AttemptNumber,
		arg.ExpiresAt,
		arg.QuestionOrder,
		arg.AnswersSnapshot,
		arg.Status,
	)
	var i CoursesQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionOrder,
		&i.ExpiresAt,
		&i.Passed,
	)
	return i, err
}

const getActiveQuizAttempt = `-- name: GetActiveQuizAttempt :one
SELECT id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed FROM courses.quiz_attempts
WHERE student_id = $1 AND quiz_id = $2 AND status = 'in_progress'
ORDER BY attempt_number DESC
LIMIT 1
`

type GetActiveQuizAttemptParams struct {
	StudentID pgtype.UUID
	QuizID    pgtype.UUID
}

// The student's current in-progress attempt at a quiz, if any. Used to resume an
// attempt and to block starting a second concurrent one.
func (q *Queries) GetActiveQuizAttempt(ctx context.Context, arg GetActiveQuizAttemptParams) (CoursesQuizAttempt, error) {
	row := q.db.QueryRow(ctx, getActiveQuizAttempt, arg.StudentID, arg.QuizID)
	var i CoursesQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionOrder,
		&i.ExpiresAt,
		&i.Passed,
	)
	return i, err
}

const getQuizAttemptByID = `-- name: GetQuizAttemptByID :one
SELECT id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed FROM courses.quiz_attempts
WHERE id = $1 AND student_id = $2
`

type GetQuizAttemptByIDParams struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
}

// Filters by student_id to prevent IDOR (Non-Negotiable #7).
func (q *Queries) GetQuizAttemptByID(ctx context.Context, arg GetQuizAttemptByIDParams) (CoursesQuizAttempt, error) {
	row := q.db.QueryRow(ctx, getQuizAttemptByID, arg.ID, arg.StudentID)
	var i CoursesQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionOrder,
		&i.ExpiresAt,
		&i.Passed,
	)
	return i, err
}

const gradeQuizAttempt = `-- name: GradeQuizAttempt :one
UPDATE courses.quiz_attempts
SET score = $2,
    percentage = $3,
    passed = $4,
    submitted_at = now(),
    status = 'graded'
WHERE id = $1
RETURNING id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed
`

type GradeQuizAttemptParams struct {
	ID         pgtype.UUID
	Score      pgtype.Numeric
	Percentage pgtype.Numeric
	Passed     *bool
}

func (q *Queries) GradeQuizAttempt(ctx context.Context, arg GradeQuizAttemptParams) (CoursesQuizAttempt, error) {
	row := q.db.QueryRow(ctx, gradeQuizAttempt,
		arg.ID,
		arg.Score,
		arg.Percentage,
		arg.Passed,
	)
	var i CoursesQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionOrder,
		&i.ExpiresAt,
		&i.Passed,
	)
	return i, err
}

const listExpiredQuizAttempts = `-- name: ListExpiredQuizAttempts :many
SELECT id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed FROM courses.quiz_attempts
WHERE status = 'in_progress'
  AND expires_at IS NOT NULL
  AND expires_at < $1
ORDER BY expires_at ASC
LIMIT $2
`

type ListExpiredQuizAttemptsParams struct {
	ExpiresAt pgtype.Timestamptz
	Limit     int32
}

// In-progress attempts whose server-side deadline has passed, for the auto-grade
// sweeper (spec §9.1 time enforcement, Non-Negotiable #2). Only timed quizzes
// (expires_at NOT NULL) are eligible.
func (q *Queries) ListExpiredQuizAttempts(ctx context.Context, arg ListExpiredQuizAttemptsParams) ([]CoursesQuizAttempt, error) {
	rows, err := q.db.Query(ctx, listExpiredQuizAttempts, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesQuizAttempt{}
	for rows.Next() {
		var i CoursesQuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.StudentID,
			&i.AttemptNumber,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.Percentage,
			&i.AnswersSnapshot,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionOrder,
			&i.ExpiresAt,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttemptsByStudentAndQuiz = `-- name: ListQuizAttemptsByStudentAndQuiz :many
SELECT id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed FROM courses.quiz_attempts
WHERE student_id = $1 AND quiz_id = $2
ORDER BY attempt_number DESC
`

type ListQuizAttemptsByStudentAndQuizParams struct {
	StudentID pgtype.UUID
	QuizID    pgtype.UUID
}

func (q *Queries) ListQuizAttemptsByStudentAndQuiz(ctx context.Context, arg ListQuizAttemptsByStudentAndQuizParams) ([]CoursesQuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttemptsByStudentAndQuiz, arg.StudentID, arg.QuizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesQuizAttempt{}
	for rows.Next() {
		var i CoursesQuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.StudentID,
			&i.AttemptNumber,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.Percentage,
			&i.AnswersSnapshot,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionOrder,
			&i.ExpiresAt,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuizAttempt = `-- name: UpdateQuizAttempt :one
UPDATE courses.quiz_attempts
SET answers_snapshot = $2,
    status = $3,
    submitted_at = $4
WHERE id = $1
RETURNING id, quiz_id, student_id, attempt_number, started_at, submitted_at, score, percentage, answers_snapshot, status, created_at, updated_at, question_order, expires_at, passed
`

type UpdateQuizAttemptParams struct {
	ID              pgtype.UUID
	AnswersSnapshot []byte
	Status          string
	SubmittedAt     pgtype.Timestamptz
}

// Auto-save (spec §9.1: state saved every 30s) and status transitions. Persists
// the latest answers snapshot and status without touching the immutable timer
// columns (started_at/expires_at).
func (q *Queries) UpdateQuizAttempt(ctx context.Context, arg UpdateQuizAttemptParams) (CoursesQuizAttempt, error) {
	row := q.db.QueryRow(ctx, updateQuizAttempt,
		arg.ID,
		arg.AnswersSnapshot,
		arg.Status,
		arg.SubmittedAt,
	)
	var i CoursesQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.Score,
		&i.Percentage,
		&i.AnswersSnapshot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionOrder,
		&i.ExpiresAt,
		&i.Passed,
	)
	return i, err
}
