// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revenue.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completedRevenueByProvider = `-- name: CompletedRevenueByProvider :many
SELECT provider,
       COALESCE(SUM(amount), 0)::numeric AS gross,
       COUNT(*)::bigint AS units
FROM payments.payments
WHERE status = 'completed'
  AND paid_at BETWEEN $1 AND $2
GROUP BY provider
ORDER BY provider
`

type CompletedRevenueByProviderParams struct {
	PaidAt   pgtype.Timestamptz
	PaidAt_2 pgtype.Timestamptz
}

type CompletedRevenueByProviderRow struct {
	Provider string
	Gross    pgtype.Numeric
	Units    int64
}

// CompletedRevenueByProvider breaks the platform gross down per provider in a
// window (for the admin revenue report).
func (q *Queries) CompletedRevenueByProvider(ctx context.Context, arg CompletedRevenueByProviderParams) ([]CompletedRevenueByProviderRow, error) {
	rows, err := q.db.Query(ctx, completedRevenueByProvider, arg.PaidAt, arg.PaidAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompletedRevenueByProviderRow{}
	for rows.Next() {
		var i CompletedRevenueByProviderRow
		if err := rows.Scan(&i.Provider, &i.Gross, &i.Units); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseSales = `-- name: CourseSales :one
SELECT COALESCE(SUM(amount), 0)::numeric AS gross,
       COUNT(*)::bigint AS units
FROM payments.payments
WHERE course_id = $1
  AND status = 'completed'
`

type CourseSalesRow struct {
	Gross pgtype.Numeric
	Units int64
}

// CourseSales is the lifetime gross + units sold for a single course.
func (q *Queries) CourseSales(ctx context.Context, courseID pgtype.UUID) (CourseSalesRow, error) {
	row := q.db.QueryRow(ctx, courseSales, courseID)
	var i CourseSalesRow
	err := row.Scan(&i.Gross, &i.Units)
	return i, err
}

const sumCompletedPayments = `-- name: SumCompletedPayments :one

SELECT COALESCE(SUM(amount), 0)::numeric AS gross,
       COUNT(*)::bigint AS units
FROM payments.payments
WHERE status = 'completed'
  AND paid_at BETWEEN $1 AND $2
`

type SumCompletedPaymentsParams struct {
	PaidAt   pgtype.Timestamptz
	PaidAt_2 pgtype.Timestamptz
}

type SumCompletedPaymentsRow struct {
	Gross pgtype.Numeric
	Units int64
}

// Revenue reporting aggregations over completed payments (spec §1.6, §10).
// All read-only; the usecase layer applies role/ownership scoping and the
// configurable teacher/platform split.
// SumCompletedPayments is the platform gross + unit count of settled payments in
// a window (keyed on paid_at, set at completion).
func (q *Queries) SumCompletedPayments(ctx context.Context, arg SumCompletedPaymentsParams) (SumCompletedPaymentsRow, error) {
	row := q.db.QueryRow(ctx, sumCompletedPayments, arg.PaidAt, arg.PaidAt_2)
	var i SumCompletedPaymentsRow
	err := row.Scan(&i.Gross, &i.Units)
	return i, err
}

const sumRefundedPayments = `-- name: SumRefundedPayments :one
SELECT COALESCE(SUM(amount), 0)::numeric AS refunded,
       COUNT(*)::bigint AS units
FROM payments.payments
WHERE status = 'refunded'
  AND updated_at BETWEEN $1 AND $2
`

type SumRefundedPaymentsParams struct {
	UpdatedAt   pgtype.Timestamptz
	UpdatedAt_2 pgtype.Timestamptz
}

type SumRefundedPaymentsRow struct {
	Refunded pgtype.Numeric
	Units    int64
}

// SumRefundedPayments is the refunded total + count in a window (keyed on the
// updated_at that stamped the refund).
func (q *Queries) SumRefundedPayments(ctx context.Context, arg SumRefundedPaymentsParams) (SumRefundedPaymentsRow, error) {
	row := q.db.QueryRow(ctx, sumRefundedPayments, arg.UpdatedAt, arg.UpdatedAt_2)
	var i SumRefundedPaymentsRow
	err := row.Scan(&i.Refunded, &i.Units)
	return i, err
}

const teacherGrossEarnings = `-- name: TeacherGrossEarnings :one
SELECT COALESCE(SUM(p.amount), 0)::numeric AS gross,
       COUNT(*)::bigint AS units
FROM payments.payments p
JOIN courses.courses c ON c.id = p.course_id
WHERE c.teacher_id = $1
  AND p.status = 'completed'
  AND p.paid_at BETWEEN $2 AND $3
`

type TeacherGrossEarningsParams struct {
	TeacherID pgtype.UUID
	PaidAt    pgtype.Timestamptz
	PaidAt_2  pgtype.Timestamptz
}

type TeacherGrossEarningsRow struct {
	Gross pgtype.Numeric
	Units int64
}

// TeacherGrossEarnings sums completed payments for the teacher's courses in a
// window; the usecase multiplies by the configured teacher share.
func (q *Queries) TeacherGrossEarnings(ctx context.Context, arg TeacherGrossEarningsParams) (TeacherGrossEarningsRow, error) {
	row := q.db.QueryRow(ctx, teacherGrossEarnings, arg.TeacherID, arg.PaidAt, arg.PaidAt_2)
	var i TeacherGrossEarningsRow
	err := row.Scan(&i.Gross, &i.Units)
	return i, err
}
