// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sections.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSection = `-- name: CreateSection :one
INSERT INTO courses.course_sections (course_id, title, description, order_index, is_published)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, title, description, order_index, is_published, created_at, updated_at, deleted_at
`

type CreateSectionParams struct {
	CourseID    pgtype.UUID
	Title       string
	Description *string
	OrderIndex  int32
	IsPublished bool
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (CoursesCourseSection, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.IsPublished,
	)
	var i CoursesCourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSectionByID = `-- name: GetSectionByID :one
SELECT id, course_id, title, description, order_index, is_published, created_at, updated_at, deleted_at FROM courses.course_sections
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSectionByID(ctx context.Context, id pgtype.UUID) (CoursesCourseSection, error) {
	row := q.db.QueryRow(ctx, getSectionByID, id)
	var i CoursesCourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSectionsByCourse = `-- name: ListSectionsByCourse :many
SELECT id, course_id, title, description, order_index, is_published, created_at, updated_at, deleted_at FROM courses.course_sections
WHERE course_id = $1 AND deleted_at IS NULL
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListSectionsByCourse(ctx context.Context, courseID pgtype.UUID) ([]CoursesCourseSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesCourseSection{}
	for rows.Next() {
		var i CoursesCourseSection
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSectionOrderIndex = `-- name: MaxSectionOrderIndex :one
SELECT COALESCE(MAX(order_index), -1)::int AS max_order_index
FROM courses.course_sections
WHERE course_id = $1 AND deleted_at IS NULL
`

// Highest order_index among a course's live sections; -1 when none exist, so
// callers can use (max + 1) for the next append position.
func (q *Queries) MaxSectionOrderIndex(ctx context.Context, courseID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxSectionOrderIndex, courseID)
	var max_order_index int32
	err := row.Scan(&max_order_index)
	return max_order_index, err
}

const softDeleteSection = `-- name: SoftDeleteSection :exec
UPDATE courses.course_sections
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSection, id)
	return err
}

const updateSection = `-- name: UpdateSection :one
UPDATE courses.course_sections
SET title = $2,
    description = $3,
    order_index = $4,
    is_published = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, course_id, title, description, order_index, is_published, created_at, updated_at, deleted_at
`

type UpdateSectionParams struct {
	ID          pgtype.UUID
	Title       string
	Description *string
	OrderIndex  int32
	IsPublished bool
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (CoursesCourseSection, error) {
	row := q.db.QueryRow(ctx, updateSection,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.IsPublished,
	)
	var i CoursesCourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
