// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sections.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSection = `-- name: CreateSection :one
INSERT INTO courses.course_sections (course_id, title, description, order_index, is_published)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, title, description, order_index, is_published, created_at, updated_at
`

type CreateSectionParams struct {
	CourseID    pgtype.UUID
	Title       string
	Description *string
	OrderIndex  int32
	IsPublished bool
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (CoursesCourseSection, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.IsPublished,
	)
	var i CoursesCourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionByID = `-- name: GetSectionByID :one
SELECT id, course_id, title, description, order_index, is_published, created_at, updated_at FROM courses.course_sections
WHERE id = $1
`

func (q *Queries) GetSectionByID(ctx context.Context, id pgtype.UUID) (CoursesCourseSection, error) {
	row := q.db.QueryRow(ctx, getSectionByID, id)
	var i CoursesCourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSectionsByCourse = `-- name: ListSectionsByCourse :many
SELECT id, course_id, title, description, order_index, is_published, created_at, updated_at FROM courses.course_sections
WHERE course_id = $1
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListSectionsByCourse(ctx context.Context, courseID pgtype.UUID) ([]CoursesCourseSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesCourseSection{}
	for rows.Next() {
		var i CoursesCourseSection
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
