// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscriptionAtPeriodEnd = `-- name: CancelSubscriptionAtPeriodEnd :execrows
UPDATE payments.subscriptions
SET canceled_at = now(),
    updated_at = now()
WHERE id = $1 AND status = 'active' AND canceled_at IS NULL
`

// CancelSubscriptionAtPeriodEnd flags an active subscription as canceled (it will
// not renew) while keeping access until current_period_end; the sweeper expires
// it once the period lapses. Guarded so a repeated cancel is a no-op.
func (q *Queries) CancelSubscriptionAtPeriodEnd(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSubscriptionAtPeriodEnd, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireLapsedSubscription = `-- name: ExpireLapsedSubscription :execrows
UPDATE payments.subscriptions
SET status = 'expired',
    updated_at = now()
WHERE id = $1 AND status = 'active' AND current_period_end <= now()
`

// ExpireLapsedSubscription transitions an active subscription whose period has
// ended to 'expired'. Guarded on status + period so a renewal that landed between
// the sweeper's list and this update is never clobbered, and a repeated tick is a
// no-op (the row is no longer active).
func (q *Queries) ExpireLapsedSubscription(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, expireLapsedSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO payments.subscriptions (
    id, student_id, plan, status, current_period_start, current_period_end,
    provider, provider_subscription_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, student_id, plan, status, current_period_start, current_period_end, provider, provider_subscription_id, created_at, updated_at, canceled_at
`

type CreateSubscriptionParams struct {
	ID                     pgtype.UUID
	StudentID              pgtype.UUID
	Plan                   string
	Status                 string
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	Provider               string
	ProviderSubscriptionID *string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (PaymentsSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.StudentID,
		arg.Plan,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.Provider,
		arg.ProviderSubscriptionID,
	)
	var i PaymentsSubscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const extendSubscriptionPeriod = `-- name: ExtendSubscriptionPeriod :exec
UPDATE payments.subscriptions
SET current_period_end = $2,
    status = 'active',
    updated_at = now()
WHERE id = $1
`

type ExtendSubscriptionPeriodParams struct {
	ID               pgtype.UUID
	CurrentPeriodEnd pgtype.Timestamptz
}

// ExtendSubscriptionPeriod pushes an active subscription's period end out (a
// renewal or stacked purchase) and (re)activates it; the period-extension
// primitive used by idempotent Activate.
func (q *Queries) ExtendSubscriptionPeriod(ctx context.Context, arg ExtendSubscriptionPeriodParams) error {
	_, err := q.db.Exec(ctx, extendSubscriptionPeriod, arg.ID, arg.CurrentPeriodEnd)
	return err
}

const getActiveSubscriptionForStudent = `-- name: GetActiveSubscriptionForStudent :one
SELECT id, student_id, plan, status, current_period_start, current_period_end, provider, provider_subscription_id, created_at, updated_at, canceled_at FROM payments.subscriptions
WHERE student_id = $1 AND status = 'active' AND current_period_end > now()
ORDER BY current_period_end DESC
LIMIT 1
`

// GetActiveSubscriptionForStudent returns the all-access subscription only when
// it grants access now (active and within its period).
func (q *Queries) GetActiveSubscriptionForStudent(ctx context.Context, studentID pgtype.UUID) (PaymentsSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionForStudent, studentID)
	var i PaymentsSubscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, student_id, plan, status, current_period_start, current_period_end, provider, provider_subscription_id, created_at, updated_at, canceled_at FROM payments.subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (PaymentsSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i PaymentsSubscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
	)
	return i, err
}

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT id, student_id, plan, status, current_period_start, current_period_end, provider, provider_subscription_id, created_at, updated_at, canceled_at FROM payments.subscriptions
WHERE status = 'active' AND current_period_end <= now()
ORDER BY current_period_end ASC
LIMIT $1
`

// ListExpiringSubscriptions returns active subscriptions whose period has ended,
// for the renewal/expiry sweeper (Skill 4).
func (q *Queries) ListExpiringSubscriptions(ctx context.Context, limit int32) ([]PaymentsSubscription, error) {
	rows, err := q.db.Query(ctx, listExpiringSubscriptions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsSubscription{}
	for rows.Next() {
		var i PaymentsSubscription
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Plan,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.Provider,
			&i.ProviderSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE payments.subscriptions
SET status = $2,
    canceled_at = CASE WHEN $2 = 'canceled' THEN now() ELSE canceled_at END,
    updated_at = now()
WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.ID, arg.Status)
	return err
}
