// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (
    email, phone, password_hash, role, first_name, last_name, avatar_url,
    is_active, is_email_verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, email, phone, password_hash, role, first_name, last_name, avatar_url, is_active, is_email_verified, email_verification_token, password_reset_token, password_reset_expires_at, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email           string
	Phone           *string
	PasswordHash    string
	Role            string
	FirstName       string
	LastName        string
	AvatarUrl       *string
	IsActive        bool
	IsEmailVerified bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.IsEmailVerified,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.EmailVerificationToken,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, password_hash, role, first_name, last_name, avatar_url, is_active, is_email_verified, email_verification_token, password_reset_token, password_reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM auth.users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.EmailVerificationToken,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, role, first_name, last_name, avatar_url, is_active, is_email_verified, email_verification_token, password_reset_token, password_reset_expires_at, last_login_at, created_at, updated_at, deleted_at FROM auth.users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.EmailVerificationToken,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setLastLogin = `-- name: SetLastLogin :exec
UPDATE auth.users
SET last_login_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SetLastLoginParams struct {
	ID          pgtype.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) SetLastLogin(ctx context.Context, arg SetLastLoginParams) error {
	_, err := q.db.Exec(ctx, setLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE auth.users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE auth.users
SET phone = $2,
    password_hash = $3,
    first_name = $4,
    last_name = $5,
    avatar_url = $6,
    is_active = $7,
    is_email_verified = $8,
    email_verification_token = $9,
    password_reset_token = $10,
    password_reset_expires_at = $11
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, phone, password_hash, role, first_name, last_name, avatar_url, is_active, is_email_verified, email_verification_token, password_reset_token, password_reset_expires_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID                     pgtype.UUID
	Phone                  *string
	PasswordHash           string
	FirstName              string
	LastName               string
	AvatarUrl              *string
	IsActive               bool
	IsEmailVerified        bool
	EmailVerificationToken *string
	PasswordResetToken     *string
	PasswordResetExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Phone,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.IsEmailVerified,
		arg.EmailVerificationToken,
		arg.PasswordResetToken,
		arg.PasswordResetExpiresAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.EmailVerificationToken,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
