// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO courses.videos (id, lesson_id, course_id, processing_status, original_file_key, file_size_bytes)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, lesson_id, original_file_key, hls_master_key, processing_status, duration_seconds, resolution_480p_key, resolution_720p_key, resolution_1080p_key, thumbnail_key, file_size_bytes, created_at, updated_at, course_id, processing_error, processed_at, deleted_at
`

type CreateVideoParams struct {
	LessonID         pgtype.UUID
	CourseID         pgtype.UUID
	ProcessingStatus string
	OriginalFileKey  *string
	FileSizeBytes    int64
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (CoursesVideo, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.LessonID,
		arg.CourseID,
		arg.ProcessingStatus,
		arg.OriginalFileKey,
		arg.FileSizeBytes,
	)
	var i CoursesVideo
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.OriginalFileKey,
		&i.HlsMasterKey,
		&i.ProcessingStatus,
		&i.DurationSeconds,
		&i.Resolution480pKey,
		&i.Resolution720pKey,
		&i.Resolution1080pKey,
		&i.ThumbnailKey,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseID,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, lesson_id, original_file_key, hls_master_key, processing_status, duration_seconds, resolution_480p_key, resolution_720p_key, resolution_1080p_key, thumbnail_key, file_size_bytes, created_at, updated_at, course_id, processing_error, processed_at, deleted_at FROM courses.videos WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVideoByID(ctx context.Context, id pgtype.UUID) (CoursesVideo, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i CoursesVideo
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.OriginalFileKey,
		&i.HlsMasterKey,
		&i.ProcessingStatus,
		&i.DurationSeconds,
		&i.Resolution480pKey,
		&i.Resolution720pKey,
		&i.Resolution1080pKey,
		&i.ThumbnailKey,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseID,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByLessonID = `-- name: GetVideoByLessonID :one
SELECT id, lesson_id, original_file_key, hls_master_key, processing_status, duration_seconds, resolution_480p_key, resolution_720p_key, resolution_1080p_key, thumbnail_key, file_size_bytes, created_at, updated_at, course_id, processing_error, processed_at, deleted_at FROM courses.videos WHERE lesson_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVideoByLessonID(ctx context.Context, lessonID pgtype.UUID) (CoursesVideo, error) {
	row := q.db.QueryRow(ctx, getVideoByLessonID, lessonID)
	var i CoursesVideo
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.OriginalFileKey,
		&i.HlsMasterKey,
		&i.ProcessingStatus,
		&i.DurationSeconds,
		&i.Resolution480pKey,
		&i.Resolution720pKey,
		&i.Resolution1080pKey,
		&i.ThumbnailKey,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseID,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVideosByStatus = `-- name: ListVideosByStatus :many
SELECT id, lesson_id, original_file_key, hls_master_key, processing_status, duration_seconds, resolution_480p_key, resolution_720p_key, resolution_1080p_key, thumbnail_key, file_size_bytes, created_at, updated_at, course_id, processing_error, processed_at, deleted_at FROM courses.videos
WHERE processing_status = $1 AND deleted_at IS NULL
ORDER BY created_at ASC LIMIT $2
`

type ListVideosByStatusParams struct {
	ProcessingStatus string
	Limit            int32
}

func (q *Queries) ListVideosByStatus(ctx context.Context, arg ListVideosByStatusParams) ([]CoursesVideo, error) {
	rows, err := q.db.Query(ctx, listVideosByStatus, arg.ProcessingStatus, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoursesVideo{}
	for rows.Next() {
		var i CoursesVideo
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.OriginalFileKey,
			&i.HlsMasterKey,
			&i.ProcessingStatus,
			&i.DurationSeconds,
			&i.Resolution480pKey,
			&i.Resolution720pKey,
			&i.Resolution1080pKey,
			&i.ThumbnailKey,
			&i.FileSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseID,
			&i.ProcessingError,
			&i.ProcessedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoReady = `-- name: SetVideoReady :one
UPDATE courses.videos
SET processing_status = 'ready',
    hls_master_key = $2, resolution_480p_key = $3, resolution_720p_key = $4,
    resolution_1080p_key = $5, thumbnail_key = $6, duration_seconds = $7,
    processed_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, lesson_id, original_file_key, hls_master_key, processing_status, duration_seconds, resolution_480p_key, resolution_720p_key, resolution_1080p_key, thumbnail_key, file_size_bytes, created_at, updated_at, course_id, processing_error, processed_at, deleted_at
`

type SetVideoReadyParams struct {
	ID                 pgtype.UUID
	HlsMasterKey       *string
	Resolution480pKey  *string
	Resolution720pKey  *string
	Resolution1080pKey *string
	ThumbnailKey       *string
	DurationSeconds    int32
}

func (q *Queries) SetVideoReady(ctx context.Context, arg SetVideoReadyParams) (CoursesVideo, error) {
	row := q.db.QueryRow(ctx, setVideoReady,
		arg.ID,
		arg.HlsMasterKey,
		arg.Resolution480pKey,
		arg.Resolution720pKey,
		arg.Resolution1080pKey,
		arg.ThumbnailKey,
		arg.DurationSeconds,
	)
	var i CoursesVideo
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.OriginalFileKey,
		&i.HlsMasterKey,
		&i.ProcessingStatus,
		&i.DurationSeconds,
		&i.Resolution480pKey,
		&i.Resolution720pKey,
		&i.Resolution1080pKey,
		&i.ThumbnailKey,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseID,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE courses.videos
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVideo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVideo, id)
	return err
}

const updateVideoStatusGuarded = `-- name: UpdateVideoStatusGuarded :execrows
UPDATE courses.videos
SET processing_status = $1, updated_at = now()
WHERE id = $2 AND processing_status = $3 AND deleted_at IS NULL
`

type UpdateVideoStatusGuardedParams struct {
	ToStatus   string
	ID         pgtype.UUID
	FromStatus string
}

// UpdateVideoStatusGuarded flips status only when the row still holds from_status;
// :execrows lets the repo report claimed=false (0 rows) without an error so two
// workers can race for the same video safely.
func (q *Queries) UpdateVideoStatusGuarded(ctx context.Context, arg UpdateVideoStatusGuardedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVideoStatusGuarded, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
