// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWebhookIfNew = `-- name: InsertWebhookIfNew :one
INSERT INTO payments.webhook_events (id, provider, provider_event_id, event_type, payload)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT (provider, provider_event_id) DO NOTHING
RETURNING id
`

type InsertWebhookIfNewParams struct {
	Provider        string
	ProviderEventID string
	EventType       string
	Payload         []byte
}

// InsertWebhookIfNew is the dedup primitive (spec §7.3). ON CONFLICT
// (provider, provider_event_id) DO NOTHING means a re-delivered event returns no
// row, signalling the caller to skip re-processing. A returned id means this is
// the first delivery and the caller should fulfill it.
func (q *Queries) InsertWebhookIfNew(ctx context.Context, arg InsertWebhookIfNewParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWebhookIfNew,
		arg.Provider,
		arg.ProviderEventID,
		arg.EventType,
		arg.Payload,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE payments.webhook_events
SET processed_at = now()
WHERE provider = $1 AND provider_event_id = $2
`

type MarkWebhookProcessedParams struct {
	Provider        string
	ProviderEventID string
}

func (q *Queries) MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, arg.Provider, arg.ProviderEventID)
	return err
}
